-- Drop existing objects if they exist, to allow for a clean setup.
DROP POLICY IF EXISTS "Users can update the status of messages sent to them" ON public.messages;
DROP POLICY IF EXISTS "Users can insert their own messages" ON public.messages;
DROP POLICY IF EXISTS "Users can view their own messages" ON public.messages;
DROP TABLE IF EXISTS public.messages;
DROP TYPE IF EXISTS public.message_status;

-- Create a custom type for message status for better data integrity.
CREATE TYPE public.message_status AS ENUM ('pending', 'delivered', 'read');

-- Create the messages table to store chat messages.
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    to_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL CHECK (char_length(content) > 0),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status public.message_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments for clarity on the table and its columns.
COMMENT ON TABLE public.messages IS 'Stores chat messages between users.';
COMMENT ON COLUMN public.messages.from_user_id IS 'The UUID of the user who sent the message.';
COMMENT ON COLUMN public.messages.to_user_id IS 'The UUID of the user who received the message.';
COMMENT ON COLUMN public.messages.content IS 'The text content of the message.';
COMMENT ON COLUMN public.messages.status IS 'The delivery status of the message (pending, delivered, or read).';

-- Create indexes for faster queries on user IDs.
CREATE INDEX idx_messages_from_user_id ON public.messages(from_user_id);
CREATE INDEX idx_messages_to_user_id ON public.messages(to_user_id);

-- Enable Row Level Security (RLS) on the messages table.
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Create RLS policies to control access to the data.

-- 1. SELECT Policy: Users can only see messages that they sent or received.
CREATE POLICY "Users can view their own messages"
ON public.messages FOR SELECT
USING (auth.uid() = from_user_id OR auth.uid() = to_user_id);

-- 2. INSERT Policy: Users can only insert messages from themselves.
CREATE POLICY "Users can insert their own messages"
ON public.messages FOR INSERT
WITH CHECK (auth.uid() = from_user_id);

-- 3. UPDATE Policy: Users can only update the status of messages sent to them (e.g., to mark as 'read').
--    This allows for future enhancements where a recipient confirms message receipt.
CREATE POLICY "Users can update the status of messages sent to them"
ON public.messages FOR UPDATE
USING (auth.uid() = to_user_id);
